package com.medical.medical.controller;

import com.medical.medical.models.Patient;
import com.medical.medical.service.PatientService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController // This means that this class is a Controller
@RequestMapping(path="/api/patient") // This means URL's start with /demo (after Application path)
public class PatientController {
    @Autowired // This means to get the bean called PatientService
    // Which is auto-generated by Spring, we will use it to handle the data
    private PatientService PatientService;


    @GetMapping(path = "/")
    public ResponseEntity<List<Patient>> getPatients(){
        try {
            List<Patient> Patients = PatientService.getPatients();
            return new ResponseEntity<>(Patients, HttpStatus.OK);
        } 
        catch (Exception e) {
            return new ResponseEntity<>(null, HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    @PostMapping(path = "/")
    public ResponseEntity<Patient> savePatient(@RequestBody Patient Patient) {
        try {
            return new ResponseEntity<>(PatientService.savePatient(Patient), HttpStatus.CREATED);
        }
        catch (Exception e){
            return new ResponseEntity<>(null, HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    @GetMapping(path = "/{id}")
    public Patient getPatientById(@PathVariable Long id) {
        return PatientService.getPatientByID(id);
    }

    @DeleteMapping(path = "/{id}")
    public void deleteById(@PathVariable Long id) {
        PatientService.deleteByID(id);
    }

    @DeleteMapping(path = "/")
    public void deleteAll() {
        PatientService.deleteAll();
    }

}
