package com.medical.medical.controller;

import com.medical.medical.models.Rdv;
import com.medical.medical.service.RdvService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController // This means that this class is a Controller
@RequestMapping(path="/api/rdv") // This means URL's start with /demo (after Application path)
public class RdvController {
    @Autowired // This means to get the bean called RdvService
    // Which is auto-generated by Spring, we will use it to handle the data
    private RdvService RdvService;


    @GetMapping(path = "/")
    public ResponseEntity<List<Rdv>> getRdvs(){
        try {
            List<Rdv> Rdvs = RdvService.getRdvs();
            return new ResponseEntity<>(Rdvs, HttpStatus.OK);
        } 
        catch (Exception e) {
            return new ResponseEntity<>(null, HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    @PostMapping(path = "/")
    public ResponseEntity<Rdv> saveRdv(@RequestBody Rdv Rdv) {
        try {
            return new ResponseEntity<>(RdvService.saveRdv(Rdv), HttpStatus.CREATED);
        }
        catch (Exception e){
            return new ResponseEntity<>(null, HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    @GetMapping(path = "/{id}")
    public Rdv getRdvById(@PathVariable Long id) {
        return RdvService.getRdvByID(id);
    }

    @DeleteMapping(path = "/{id}")
    public void deleteById(@PathVariable Long id) {
        RdvService.deleteByID(id);
    }

    @DeleteMapping(path = "/")
    public void deleteAll() {
        RdvService.deleteAll();
    }

}